version: 2.1

orbs:
  architect: giantswarm/architect@5.0.0
  orb-tools: circleci/orb-tools@9.3.0

workflows:
  catalog_build:
    jobs:
      - architect/changelog-lint

      - orb-tools/lint:
          filters:
            tags:
              only: /.*/

      - orb-tools/pack:
          source-dir: src
          destination-orb-path: packed/orb.yml
          workspace-path: packed/orb.yml
          artifact-path: packed/orb.yml
          requires: [orb-tools/lint]
          filters:
            tags:
              only: /.*/

      - orb-tools/publish:
          name: publish-branch
          attach-workspace: true
          orb-path: workspace/packed/orb.yml
          orb-ref: giantswarm/architect@dev:${CIRCLE_BRANCH}
          publish-token-variable: CIRCLECI_DEV_API_TOKEN
          requires: [orb-tools/pack]
          filters:
            branches:
              only: /.*/
            tags:
              ignore: /.*/

      - orb-tools/publish:
          name: publish-tag
          attach-workspace: true
          orb-path: workspace/packed/orb.yml
          orb-ref: giantswarm/architect@${CIRCLE_TAG##v}
          publish-token-variable: CIRCLECI_DEV_API_TOKEN
          requires: [orb-tools/pack]
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v\d+\.\d+\.\d+$/
