version: 2.1

orbs:
  architect: giantswarm/architect@5.0.0
  orb-tools: circleci/orb-tools@12.0.4

workflows:
  catalog_build:
    jobs:
      - architect/changelog-lint

      - orb-tools/lint:
          filters:
            tags:
              only: /.*/

      - orb-tools/pack:
          source-dir: src
          requires:
            - "orb-tools/lint"
          filters:
            tags:
              only: /.*/

      - orb-tools/publish:
          name: publish-branch
          orb-name: giantswarm/architect
          vcs-type: github
          circleci-token: CIRCLECI_DEV_API_TOKEN
          requires:
            - "orb-tools/pack"
          filters:
            branches:
              only: /.*/
            tags:
              ignore: /.*/

      - orb-tools/publish:
          name: publish-tag
          orb-name: giantswarm/architect
          vcs-type: github
          circleci-token: CIRCLECI_DEV_API_TOKEN
          requires:
            - "orb-tools/pack"
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v\d+\.\d+\.\d+$/
