version: 2.1

orbs:
  orb-tools: circleci/orb-tools@8.3.0

workflows:
  catalog_build:
    jobs:
      - orb-tools/lint:
          filters:
            tags:
              only: /.*/

      - orb-tools/pack:
          source-dir: src
          destination-orb-path: packed/orb.yml
          workspace-path: packed/orb.yml
          artifact-path: packed/orb.yml
          requires: [orb-tools/lint]
          filters:
            tags:
              only: /.*/

      - orb-tools/publish-dev:
          orb-name: giantswarm/architect
          orb-path: workspace/packed/orb.yml
          publish-token-variable: CIRCLECI_DEV_API_TOKEN
          requires: [orb-tools/pack]

      - orb-tools/publish:
          attach-workspace: true
          orb-path: workspace/packed/orb.yml
          orb-ref: giantswarm/architect@${CIRCLE_TAG##v}
          publish-token-variable: CIRCLECI_DEV_API_TOKEN
          requires: [orb-tools/pack]
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
