version: 2.1

orbs:
  architect: giantswarm/architect@6.0.0
  orb-tools: circleci/orb-tools@12.3.1

workflows:
  catalog_build:
    jobs:
      - architect/changelog-lint

      - orb-tools/lint:
          filters:
            tags:
              only: /.*/

      - orb-tools/pack:
          requires:
            - "orb-tools/lint"
          filters:
            tags:
              only: /.*/

      - orb-tools/publish:
          name: publish-branch
          orb_name: giantswarm/architect
          vcs_type: github
          circleci_token: CIRCLECI_DEV_API_TOKEN
          requires:
            - "orb-tools/pack"
          filters:
            branches:
              only: /.*/
            tags:
              ignore: /.*/

      - orb-tools/publish:
          name: publish-tag
          orb_name: giantswarm/architect
          vcs_type: github
          circleci_token: CIRCLECI_DEV_API_TOKEN
          pub_type: production
          requires:
            - "orb-tools/pack"
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v\d+\.\d+\.\d+$/
